default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    track = options[:track] || "internal"
    
    upload_to_play_store(
      track: track,
      package_name: "com.takamagahara.tsundoku_quest",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
